#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="mihrimah_m")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void Insertbanyo(banyo instance);
  partial void Updatebanyo(banyo instance);
  partial void Deletebanyo(banyo instance);
  partial void Insertcocuk_odasi(cocuk_odasi instance);
  partial void Updatecocuk_odasi(cocuk_odasi instance);
  partial void Deletecocuk_odasi(cocuk_odasi instance);
  partial void Insertcok_amacli(cok_amacli instance);
  partial void Updatecok_amacli(cok_amacli instance);
  partial void Deletecok_amacli(cok_amacli instance);
  partial void Insertmutfak(mutfak instance);
  partial void Updatemutfak(mutfak instance);
  partial void Deletemutfak(mutfak instance);
  partial void Insertoturma_odasi(oturma_odasi instance);
  partial void Updateoturma_odasi(oturma_odasi instance);
  partial void Deleteoturma_odasi(oturma_odasi instance);
  partial void Insertuyeol(uyeol instance);
  partial void Updateuyeol(uyeol instance);
  partial void Deleteuyeol(uyeol instance);
  partial void Insertyatak_odasi(yatak_odasi instance);
  partial void Updateyatak_odasi(yatak_odasi instance);
  partial void Deleteyatak_odasi(yatak_odasi instance);
  partial void Insertyemek_odasi(yemek_odasi instance);
  partial void Updateyemek_odasi(yemek_odasi instance);
  partial void Deleteyemek_odasi(yemek_odasi instance);
  partial void Insertyonetici(yonetici instance);
  partial void Updateyonetici(yonetici instance);
  partial void Deleteyonetici(yonetici instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["mihrimah_mConnectionString1"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<banyo> banyos
	{
		get
		{
			return this.GetTable<banyo>();
		}
	}
	
	public System.Data.Linq.Table<cocuk_odasi> cocuk_odasis
	{
		get
		{
			return this.GetTable<cocuk_odasi>();
		}
	}
	
	public System.Data.Linq.Table<cok_amacli> cok_amaclis
	{
		get
		{
			return this.GetTable<cok_amacli>();
		}
	}
	
	public System.Data.Linq.Table<mutfak> mutfaks
	{
		get
		{
			return this.GetTable<mutfak>();
		}
	}
	
	public System.Data.Linq.Table<oturma_odasi> oturma_odasis
	{
		get
		{
			return this.GetTable<oturma_odasi>();
		}
	}
	
	public System.Data.Linq.Table<urun> uruns
	{
		get
		{
			return this.GetTable<urun>();
		}
	}
	
	public System.Data.Linq.Table<uyeol> uyeols
	{
		get
		{
			return this.GetTable<uyeol>();
		}
	}
	
	public System.Data.Linq.Table<yatak_odasi> yatak_odasis
	{
		get
		{
			return this.GetTable<yatak_odasi>();
		}
	}
	
	public System.Data.Linq.Table<yemek_odasi> yemek_odasis
	{
		get
		{
			return this.GetTable<yemek_odasi>();
		}
	}
	
	public System.Data.Linq.Table<yonetici> yoneticis
	{
		get
		{
			return this.GetTable<yonetici>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.banyo")]
public partial class banyo : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _no;
	
	private string _m_adi;
	
	private string _m_resim_yolu;
	
	private string _m_boyut;
	
	private string _m_renk;
	
	private string _agac_cinsi;
	
	private string _fiyat;
	
	private string _indirim_fiyat;
	
	private string _kategori;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnoChanging(string value);
    partial void OnnoChanged();
    partial void Onm_adiChanging(string value);
    partial void Onm_adiChanged();
    partial void Onm_resim_yoluChanging(string value);
    partial void Onm_resim_yoluChanged();
    partial void Onm_boyutChanging(string value);
    partial void Onm_boyutChanged();
    partial void Onm_renkChanging(string value);
    partial void Onm_renkChanged();
    partial void Onagac_cinsiChanging(string value);
    partial void Onagac_cinsiChanged();
    partial void OnfiyatChanging(string value);
    partial void OnfiyatChanged();
    partial void Onindirim_fiyatChanging(string value);
    partial void Onindirim_fiyatChanged();
    partial void OnkategoriChanging(string value);
    partial void OnkategoriChanged();
    #endregion
	
	public banyo()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_no", DbType="NVarChar(50)")]
	public string no
	{
		get
		{
			return this._no;
		}
		set
		{
			if ((this._no != value))
			{
				this.OnnoChanging(value);
				this.SendPropertyChanging();
				this._no = value;
				this.SendPropertyChanged("no");
				this.OnnoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_m_adi", DbType="NVarChar(50)")]
	public string m_adi
	{
		get
		{
			return this._m_adi;
		}
		set
		{
			if ((this._m_adi != value))
			{
				this.Onm_adiChanging(value);
				this.SendPropertyChanging();
				this._m_adi = value;
				this.SendPropertyChanged("m_adi");
				this.Onm_adiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_m_resim_yolu", DbType="NVarChar(200)")]
	public string m_resim_yolu
	{
		get
		{
			return this._m_resim_yolu;
		}
		set
		{
			if ((this._m_resim_yolu != value))
			{
				this.Onm_resim_yoluChanging(value);
				this.SendPropertyChanging();
				this._m_resim_yolu = value;
				this.SendPropertyChanged("m_resim_yolu");
				this.Onm_resim_yoluChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_m_boyut", DbType="NVarChar(50)")]
	public string m_boyut
	{
		get
		{
			return this._m_boyut;
		}
		set
		{
			if ((this._m_boyut != value))
			{
				this.Onm_boyutChanging(value);
				this.SendPropertyChanging();
				this._m_boyut = value;
				this.SendPropertyChanged("m_boyut");
				this.Onm_boyutChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_m_renk", DbType="NVarChar(50)")]
	public string m_renk
	{
		get
		{
			return this._m_renk;
		}
		set
		{
			if ((this._m_renk != value))
			{
				this.Onm_renkChanging(value);
				this.SendPropertyChanging();
				this._m_renk = value;
				this.SendPropertyChanged("m_renk");
				this.Onm_renkChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_agac_cinsi", DbType="NVarChar(50)")]
	public string agac_cinsi
	{
		get
		{
			return this._agac_cinsi;
		}
		set
		{
			if ((this._agac_cinsi != value))
			{
				this.Onagac_cinsiChanging(value);
				this.SendPropertyChanging();
				this._agac_cinsi = value;
				this.SendPropertyChanged("agac_cinsi");
				this.Onagac_cinsiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fiyat", DbType="NVarChar(50)")]
	public string fiyat
	{
		get
		{
			return this._fiyat;
		}
		set
		{
			if ((this._fiyat != value))
			{
				this.OnfiyatChanging(value);
				this.SendPropertyChanging();
				this._fiyat = value;
				this.SendPropertyChanged("fiyat");
				this.OnfiyatChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_indirim_fiyat", DbType="NVarChar(50)")]
	public string indirim_fiyat
	{
		get
		{
			return this._indirim_fiyat;
		}
		set
		{
			if ((this._indirim_fiyat != value))
			{
				this.Onindirim_fiyatChanging(value);
				this.SendPropertyChanging();
				this._indirim_fiyat = value;
				this.SendPropertyChanged("indirim_fiyat");
				this.Onindirim_fiyatChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kategori", DbType="NVarChar(50)")]
	public string kategori
	{
		get
		{
			return this._kategori;
		}
		set
		{
			if ((this._kategori != value))
			{
				this.OnkategoriChanging(value);
				this.SendPropertyChanging();
				this._kategori = value;
				this.SendPropertyChanged("kategori");
				this.OnkategoriChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.cocuk_odasi")]
public partial class cocuk_odasi : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _no;
	
	private string _m_adi;
	
	private string _m_resim_yolu;
	
	private string _m_boyut;
	
	private string _m_renk;
	
	private string _kumas_adi;
	
	private string _kumas_renk;
	
	private string _kumas_resim_yolu;
	
	private string _agac_cinsi;
	
	private string _fiyat;
	
	private string _indirim_fiyat;
	
	private string _kategori;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnoChanging(string value);
    partial void OnnoChanged();
    partial void Onm_adiChanging(string value);
    partial void Onm_adiChanged();
    partial void Onm_resim_yoluChanging(string value);
    partial void Onm_resim_yoluChanged();
    partial void Onm_boyutChanging(string value);
    partial void Onm_boyutChanged();
    partial void Onm_renkChanging(string value);
    partial void Onm_renkChanged();
    partial void Onkumas_adiChanging(string value);
    partial void Onkumas_adiChanged();
    partial void Onkumas_renkChanging(string value);
    partial void Onkumas_renkChanged();
    partial void Onkumas_resim_yoluChanging(string value);
    partial void Onkumas_resim_yoluChanged();
    partial void Onagac_cinsiChanging(string value);
    partial void Onagac_cinsiChanged();
    partial void OnfiyatChanging(string value);
    partial void OnfiyatChanged();
    partial void Onindirim_fiyatChanging(string value);
    partial void Onindirim_fiyatChanged();
    partial void OnkategoriChanging(string value);
    partial void OnkategoriChanged();
    #endregion
	
	public cocuk_odasi()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_no", DbType="NVarChar(50)")]
	public string no
	{
		get
		{
			return this._no;
		}
		set
		{
			if ((this._no != value))
			{
				this.OnnoChanging(value);
				this.SendPropertyChanging();
				this._no = value;
				this.SendPropertyChanged("no");
				this.OnnoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_m_adi", DbType="NVarChar(50)")]
	public string m_adi
	{
		get
		{
			return this._m_adi;
		}
		set
		{
			if ((this._m_adi != value))
			{
				this.Onm_adiChanging(value);
				this.SendPropertyChanging();
				this._m_adi = value;
				this.SendPropertyChanged("m_adi");
				this.Onm_adiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_m_resim_yolu", DbType="NVarChar(200)")]
	public string m_resim_yolu
	{
		get
		{
			return this._m_resim_yolu;
		}
		set
		{
			if ((this._m_resim_yolu != value))
			{
				this.Onm_resim_yoluChanging(value);
				this.SendPropertyChanging();
				this._m_resim_yolu = value;
				this.SendPropertyChanged("m_resim_yolu");
				this.Onm_resim_yoluChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_m_boyut", DbType="NVarChar(50)")]
	public string m_boyut
	{
		get
		{
			return this._m_boyut;
		}
		set
		{
			if ((this._m_boyut != value))
			{
				this.Onm_boyutChanging(value);
				this.SendPropertyChanging();
				this._m_boyut = value;
				this.SendPropertyChanged("m_boyut");
				this.Onm_boyutChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_m_renk", DbType="NVarChar(50)")]
	public string m_renk
	{
		get
		{
			return this._m_renk;
		}
		set
		{
			if ((this._m_renk != value))
			{
				this.Onm_renkChanging(value);
				this.SendPropertyChanging();
				this._m_renk = value;
				this.SendPropertyChanged("m_renk");
				this.Onm_renkChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kumas_adi", DbType="NVarChar(50)")]
	public string kumas_adi
	{
		get
		{
			return this._kumas_adi;
		}
		set
		{
			if ((this._kumas_adi != value))
			{
				this.Onkumas_adiChanging(value);
				this.SendPropertyChanging();
				this._kumas_adi = value;
				this.SendPropertyChanged("kumas_adi");
				this.Onkumas_adiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kumas_renk", DbType="NVarChar(50)")]
	public string kumas_renk
	{
		get
		{
			return this._kumas_renk;
		}
		set
		{
			if ((this._kumas_renk != value))
			{
				this.Onkumas_renkChanging(value);
				this.SendPropertyChanging();
				this._kumas_renk = value;
				this.SendPropertyChanged("kumas_renk");
				this.Onkumas_renkChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kumas_resim_yolu", DbType="NVarChar(200)")]
	public string kumas_resim_yolu
	{
		get
		{
			return this._kumas_resim_yolu;
		}
		set
		{
			if ((this._kumas_resim_yolu != value))
			{
				this.Onkumas_resim_yoluChanging(value);
				this.SendPropertyChanging();
				this._kumas_resim_yolu = value;
				this.SendPropertyChanged("kumas_resim_yolu");
				this.Onkumas_resim_yoluChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_agac_cinsi", DbType="NVarChar(50)")]
	public string agac_cinsi
	{
		get
		{
			return this._agac_cinsi;
		}
		set
		{
			if ((this._agac_cinsi != value))
			{
				this.Onagac_cinsiChanging(value);
				this.SendPropertyChanging();
				this._agac_cinsi = value;
				this.SendPropertyChanged("agac_cinsi");
				this.Onagac_cinsiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fiyat", DbType="NVarChar(50)")]
	public string fiyat
	{
		get
		{
			return this._fiyat;
		}
		set
		{
			if ((this._fiyat != value))
			{
				this.OnfiyatChanging(value);
				this.SendPropertyChanging();
				this._fiyat = value;
				this.SendPropertyChanged("fiyat");
				this.OnfiyatChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_indirim_fiyat", DbType="NVarChar(50)")]
	public string indirim_fiyat
	{
		get
		{
			return this._indirim_fiyat;
		}
		set
		{
			if ((this._indirim_fiyat != value))
			{
				this.Onindirim_fiyatChanging(value);
				this.SendPropertyChanging();
				this._indirim_fiyat = value;
				this.SendPropertyChanged("indirim_fiyat");
				this.Onindirim_fiyatChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kategori", DbType="NVarChar(50)")]
	public string kategori
	{
		get
		{
			return this._kategori;
		}
		set
		{
			if ((this._kategori != value))
			{
				this.OnkategoriChanging(value);
				this.SendPropertyChanging();
				this._kategori = value;
				this.SendPropertyChanged("kategori");
				this.OnkategoriChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.cok_amacli")]
public partial class cok_amacli : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _no;
	
	private string _m_adi;
	
	private string _m_resim_yolu;
	
	private string _m_boyut;
	
	private string _m_renk;
	
	private string _kumas_adi;
	
	private string _kumas_renk;
	
	private string _agac_cinsi;
	
	private string _fiyat;
	
	private string _indirim_fiyat;
	
	private string _kategori;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnoChanging(string value);
    partial void OnnoChanged();
    partial void Onm_adiChanging(string value);
    partial void Onm_adiChanged();
    partial void Onm_resim_yoluChanging(string value);
    partial void Onm_resim_yoluChanged();
    partial void Onm_boyutChanging(string value);
    partial void Onm_boyutChanged();
    partial void Onm_renkChanging(string value);
    partial void Onm_renkChanged();
    partial void Onkumas_adiChanging(string value);
    partial void Onkumas_adiChanged();
    partial void Onkumas_renkChanging(string value);
    partial void Onkumas_renkChanged();
    partial void Onagac_cinsiChanging(string value);
    partial void Onagac_cinsiChanged();
    partial void OnfiyatChanging(string value);
    partial void OnfiyatChanged();
    partial void Onindirim_fiyatChanging(string value);
    partial void Onindirim_fiyatChanged();
    partial void OnkategoriChanging(string value);
    partial void OnkategoriChanged();
    #endregion
	
	public cok_amacli()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_no", DbType="NVarChar(50)")]
	public string no
	{
		get
		{
			return this._no;
		}
		set
		{
			if ((this._no != value))
			{
				this.OnnoChanging(value);
				this.SendPropertyChanging();
				this._no = value;
				this.SendPropertyChanged("no");
				this.OnnoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_m_adi", DbType="NVarChar(50)")]
	public string m_adi
	{
		get
		{
			return this._m_adi;
		}
		set
		{
			if ((this._m_adi != value))
			{
				this.Onm_adiChanging(value);
				this.SendPropertyChanging();
				this._m_adi = value;
				this.SendPropertyChanged("m_adi");
				this.Onm_adiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_m_resim_yolu", DbType="NVarChar(200)")]
	public string m_resim_yolu
	{
		get
		{
			return this._m_resim_yolu;
		}
		set
		{
			if ((this._m_resim_yolu != value))
			{
				this.Onm_resim_yoluChanging(value);
				this.SendPropertyChanging();
				this._m_resim_yolu = value;
				this.SendPropertyChanged("m_resim_yolu");
				this.Onm_resim_yoluChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_m_boyut", DbType="NVarChar(50)")]
	public string m_boyut
	{
		get
		{
			return this._m_boyut;
		}
		set
		{
			if ((this._m_boyut != value))
			{
				this.Onm_boyutChanging(value);
				this.SendPropertyChanging();
				this._m_boyut = value;
				this.SendPropertyChanged("m_boyut");
				this.Onm_boyutChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_m_renk", DbType="NVarChar(50)")]
	public string m_renk
	{
		get
		{
			return this._m_renk;
		}
		set
		{
			if ((this._m_renk != value))
			{
				this.Onm_renkChanging(value);
				this.SendPropertyChanging();
				this._m_renk = value;
				this.SendPropertyChanged("m_renk");
				this.Onm_renkChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kumas_adi", DbType="NVarChar(50)")]
	public string kumas_adi
	{
		get
		{
			return this._kumas_adi;
		}
		set
		{
			if ((this._kumas_adi != value))
			{
				this.Onkumas_adiChanging(value);
				this.SendPropertyChanging();
				this._kumas_adi = value;
				this.SendPropertyChanged("kumas_adi");
				this.Onkumas_adiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kumas_renk", DbType="NVarChar(50)")]
	public string kumas_renk
	{
		get
		{
			return this._kumas_renk;
		}
		set
		{
			if ((this._kumas_renk != value))
			{
				this.Onkumas_renkChanging(value);
				this.SendPropertyChanging();
				this._kumas_renk = value;
				this.SendPropertyChanged("kumas_renk");
				this.Onkumas_renkChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_agac_cinsi", DbType="NVarChar(50)")]
	public string agac_cinsi
	{
		get
		{
			return this._agac_cinsi;
		}
		set
		{
			if ((this._agac_cinsi != value))
			{
				this.Onagac_cinsiChanging(value);
				this.SendPropertyChanging();
				this._agac_cinsi = value;
				this.SendPropertyChanged("agac_cinsi");
				this.Onagac_cinsiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fiyat", DbType="NVarChar(50)")]
	public string fiyat
	{
		get
		{
			return this._fiyat;
		}
		set
		{
			if ((this._fiyat != value))
			{
				this.OnfiyatChanging(value);
				this.SendPropertyChanging();
				this._fiyat = value;
				this.SendPropertyChanged("fiyat");
				this.OnfiyatChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_indirim_fiyat", DbType="NVarChar(50)")]
	public string indirim_fiyat
	{
		get
		{
			return this._indirim_fiyat;
		}
		set
		{
			if ((this._indirim_fiyat != value))
			{
				this.Onindirim_fiyatChanging(value);
				this.SendPropertyChanging();
				this._indirim_fiyat = value;
				this.SendPropertyChanged("indirim_fiyat");
				this.Onindirim_fiyatChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kategori", DbType="NVarChar(50)")]
	public string kategori
	{
		get
		{
			return this._kategori;
		}
		set
		{
			if ((this._kategori != value))
			{
				this.OnkategoriChanging(value);
				this.SendPropertyChanging();
				this._kategori = value;
				this.SendPropertyChanged("kategori");
				this.OnkategoriChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.mutfak")]
public partial class mutfak : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _no;
	
	private string _m_adi;
	
	private string _m_resim_yolu;
	
	private string _m_boyut;
	
	private string _m_renk;
	
	private string _kumas_adi;
	
	private string _kumas_renk;
	
	private string _kumas_resim_yolu;
	
	private string _agac_cinsi;
	
	private string _fiyat;
	
	private string _indirim_fiyat;
	
	private string _kategori;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnoChanging(string value);
    partial void OnnoChanged();
    partial void Onm_adiChanging(string value);
    partial void Onm_adiChanged();
    partial void Onm_resim_yoluChanging(string value);
    partial void Onm_resim_yoluChanged();
    partial void Onm_boyutChanging(string value);
    partial void Onm_boyutChanged();
    partial void Onm_renkChanging(string value);
    partial void Onm_renkChanged();
    partial void Onkumas_adiChanging(string value);
    partial void Onkumas_adiChanged();
    partial void Onkumas_renkChanging(string value);
    partial void Onkumas_renkChanged();
    partial void Onkumas_resim_yoluChanging(string value);
    partial void Onkumas_resim_yoluChanged();
    partial void Onagac_cinsiChanging(string value);
    partial void Onagac_cinsiChanged();
    partial void OnfiyatChanging(string value);
    partial void OnfiyatChanged();
    partial void Onindirim_fiyatChanging(string value);
    partial void Onindirim_fiyatChanged();
    partial void OnkategoriChanging(string value);
    partial void OnkategoriChanged();
    #endregion
	
	public mutfak()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_no", DbType="NVarChar(50)")]
	public string no
	{
		get
		{
			return this._no;
		}
		set
		{
			if ((this._no != value))
			{
				this.OnnoChanging(value);
				this.SendPropertyChanging();
				this._no = value;
				this.SendPropertyChanged("no");
				this.OnnoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_m_adi", DbType="NVarChar(50)")]
	public string m_adi
	{
		get
		{
			return this._m_adi;
		}
		set
		{
			if ((this._m_adi != value))
			{
				this.Onm_adiChanging(value);
				this.SendPropertyChanging();
				this._m_adi = value;
				this.SendPropertyChanged("m_adi");
				this.Onm_adiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_m_resim_yolu", DbType="NVarChar(200)")]
	public string m_resim_yolu
	{
		get
		{
			return this._m_resim_yolu;
		}
		set
		{
			if ((this._m_resim_yolu != value))
			{
				this.Onm_resim_yoluChanging(value);
				this.SendPropertyChanging();
				this._m_resim_yolu = value;
				this.SendPropertyChanged("m_resim_yolu");
				this.Onm_resim_yoluChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_m_boyut", DbType="NVarChar(50)")]
	public string m_boyut
	{
		get
		{
			return this._m_boyut;
		}
		set
		{
			if ((this._m_boyut != value))
			{
				this.Onm_boyutChanging(value);
				this.SendPropertyChanging();
				this._m_boyut = value;
				this.SendPropertyChanged("m_boyut");
				this.Onm_boyutChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_m_renk", DbType="NVarChar(50)")]
	public string m_renk
	{
		get
		{
			return this._m_renk;
		}
		set
		{
			if ((this._m_renk != value))
			{
				this.Onm_renkChanging(value);
				this.SendPropertyChanging();
				this._m_renk = value;
				this.SendPropertyChanged("m_renk");
				this.Onm_renkChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kumas_adi", DbType="NVarChar(50)")]
	public string kumas_adi
	{
		get
		{
			return this._kumas_adi;
		}
		set
		{
			if ((this._kumas_adi != value))
			{
				this.Onkumas_adiChanging(value);
				this.SendPropertyChanging();
				this._kumas_adi = value;
				this.SendPropertyChanged("kumas_adi");
				this.Onkumas_adiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kumas_renk", DbType="NVarChar(50)")]
	public string kumas_renk
	{
		get
		{
			return this._kumas_renk;
		}
		set
		{
			if ((this._kumas_renk != value))
			{
				this.Onkumas_renkChanging(value);
				this.SendPropertyChanging();
				this._kumas_renk = value;
				this.SendPropertyChanged("kumas_renk");
				this.Onkumas_renkChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kumas_resim_yolu", DbType="NVarChar(200)")]
	public string kumas_resim_yolu
	{
		get
		{
			return this._kumas_resim_yolu;
		}
		set
		{
			if ((this._kumas_resim_yolu != value))
			{
				this.Onkumas_resim_yoluChanging(value);
				this.SendPropertyChanging();
				this._kumas_resim_yolu = value;
				this.SendPropertyChanged("kumas_resim_yolu");
				this.Onkumas_resim_yoluChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_agac_cinsi", DbType="NVarChar(50)")]
	public string agac_cinsi
	{
		get
		{
			return this._agac_cinsi;
		}
		set
		{
			if ((this._agac_cinsi != value))
			{
				this.Onagac_cinsiChanging(value);
				this.SendPropertyChanging();
				this._agac_cinsi = value;
				this.SendPropertyChanged("agac_cinsi");
				this.Onagac_cinsiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fiyat", DbType="NVarChar(50)")]
	public string fiyat
	{
		get
		{
			return this._fiyat;
		}
		set
		{
			if ((this._fiyat != value))
			{
				this.OnfiyatChanging(value);
				this.SendPropertyChanging();
				this._fiyat = value;
				this.SendPropertyChanged("fiyat");
				this.OnfiyatChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_indirim_fiyat", DbType="NVarChar(50)")]
	public string indirim_fiyat
	{
		get
		{
			return this._indirim_fiyat;
		}
		set
		{
			if ((this._indirim_fiyat != value))
			{
				this.Onindirim_fiyatChanging(value);
				this.SendPropertyChanging();
				this._indirim_fiyat = value;
				this.SendPropertyChanged("indirim_fiyat");
				this.Onindirim_fiyatChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kategori", DbType="NVarChar(50)")]
	public string kategori
	{
		get
		{
			return this._kategori;
		}
		set
		{
			if ((this._kategori != value))
			{
				this.OnkategoriChanging(value);
				this.SendPropertyChanging();
				this._kategori = value;
				this.SendPropertyChanged("kategori");
				this.OnkategoriChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.oturma_odasi")]
public partial class oturma_odasi : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _no;
	
	private string _m_adi;
	
	private string _m_resim_yolu;
	
	private string _m_boyut;
	
	private string _m_renk;
	
	private string _kumas_adi;
	
	private string _kumas_renk;
	
	private string _agac_cinsi;
	
	private string _fiyat;
	
	private string _indirim_fiyat;
	
	private string _kategori;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnoChanging(string value);
    partial void OnnoChanged();
    partial void Onm_adiChanging(string value);
    partial void Onm_adiChanged();
    partial void Onm_resim_yoluChanging(string value);
    partial void Onm_resim_yoluChanged();
    partial void Onm_boyutChanging(string value);
    partial void Onm_boyutChanged();
    partial void Onm_renkChanging(string value);
    partial void Onm_renkChanged();
    partial void Onkumas_adiChanging(string value);
    partial void Onkumas_adiChanged();
    partial void Onkumas_renkChanging(string value);
    partial void Onkumas_renkChanged();
    partial void Onagac_cinsiChanging(string value);
    partial void Onagac_cinsiChanged();
    partial void OnfiyatChanging(string value);
    partial void OnfiyatChanged();
    partial void Onindirim_fiyatChanging(string value);
    partial void Onindirim_fiyatChanged();
    partial void OnkategoriChanging(string value);
    partial void OnkategoriChanged();
    #endregion
	
	public oturma_odasi()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_no", DbType="NVarChar(50)")]
	public string no
	{
		get
		{
			return this._no;
		}
		set
		{
			if ((this._no != value))
			{
				this.OnnoChanging(value);
				this.SendPropertyChanging();
				this._no = value;
				this.SendPropertyChanged("no");
				this.OnnoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_m_adi", DbType="NVarChar(50)")]
	public string m_adi
	{
		get
		{
			return this._m_adi;
		}
		set
		{
			if ((this._m_adi != value))
			{
				this.Onm_adiChanging(value);
				this.SendPropertyChanging();
				this._m_adi = value;
				this.SendPropertyChanged("m_adi");
				this.Onm_adiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_m_resim_yolu", DbType="NVarChar(200)")]
	public string m_resim_yolu
	{
		get
		{
			return this._m_resim_yolu;
		}
		set
		{
			if ((this._m_resim_yolu != value))
			{
				this.Onm_resim_yoluChanging(value);
				this.SendPropertyChanging();
				this._m_resim_yolu = value;
				this.SendPropertyChanged("m_resim_yolu");
				this.Onm_resim_yoluChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_m_boyut", DbType="NVarChar(50)")]
	public string m_boyut
	{
		get
		{
			return this._m_boyut;
		}
		set
		{
			if ((this._m_boyut != value))
			{
				this.Onm_boyutChanging(value);
				this.SendPropertyChanging();
				this._m_boyut = value;
				this.SendPropertyChanged("m_boyut");
				this.Onm_boyutChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_m_renk", DbType="NVarChar(50)")]
	public string m_renk
	{
		get
		{
			return this._m_renk;
		}
		set
		{
			if ((this._m_renk != value))
			{
				this.Onm_renkChanging(value);
				this.SendPropertyChanging();
				this._m_renk = value;
				this.SendPropertyChanged("m_renk");
				this.Onm_renkChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kumas_adi", DbType="NVarChar(50)")]
	public string kumas_adi
	{
		get
		{
			return this._kumas_adi;
		}
		set
		{
			if ((this._kumas_adi != value))
			{
				this.Onkumas_adiChanging(value);
				this.SendPropertyChanging();
				this._kumas_adi = value;
				this.SendPropertyChanged("kumas_adi");
				this.Onkumas_adiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kumas_renk", DbType="NVarChar(50)")]
	public string kumas_renk
	{
		get
		{
			return this._kumas_renk;
		}
		set
		{
			if ((this._kumas_renk != value))
			{
				this.Onkumas_renkChanging(value);
				this.SendPropertyChanging();
				this._kumas_renk = value;
				this.SendPropertyChanged("kumas_renk");
				this.Onkumas_renkChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_agac_cinsi", DbType="NVarChar(50)")]
	public string agac_cinsi
	{
		get
		{
			return this._agac_cinsi;
		}
		set
		{
			if ((this._agac_cinsi != value))
			{
				this.Onagac_cinsiChanging(value);
				this.SendPropertyChanging();
				this._agac_cinsi = value;
				this.SendPropertyChanged("agac_cinsi");
				this.Onagac_cinsiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fiyat", DbType="NVarChar(50)")]
	public string fiyat
	{
		get
		{
			return this._fiyat;
		}
		set
		{
			if ((this._fiyat != value))
			{
				this.OnfiyatChanging(value);
				this.SendPropertyChanging();
				this._fiyat = value;
				this.SendPropertyChanged("fiyat");
				this.OnfiyatChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_indirim_fiyat", DbType="NVarChar(50)")]
	public string indirim_fiyat
	{
		get
		{
			return this._indirim_fiyat;
		}
		set
		{
			if ((this._indirim_fiyat != value))
			{
				this.Onindirim_fiyatChanging(value);
				this.SendPropertyChanging();
				this._indirim_fiyat = value;
				this.SendPropertyChanged("indirim_fiyat");
				this.Onindirim_fiyatChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kategori", DbType="NVarChar(50)")]
	public string kategori
	{
		get
		{
			return this._kategori;
		}
		set
		{
			if ((this._kategori != value))
			{
				this.OnkategoriChanging(value);
				this.SendPropertyChanging();
				this._kategori = value;
				this.SendPropertyChanged("kategori");
				this.OnkategoriChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.urun")]
public partial class urun
{
	
	private System.Nullable<int> _id;
	
	private string _no;
	
	private string _resim_yolu;
	
	public urun()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int")]
	public System.Nullable<int> id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this._id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_no", DbType="NVarChar(50)")]
	public string no
	{
		get
		{
			return this._no;
		}
		set
		{
			if ((this._no != value))
			{
				this._no = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_resim_yolu", DbType="NVarChar(200)")]
	public string resim_yolu
	{
		get
		{
			return this._resim_yolu;
		}
		set
		{
			if ((this._resim_yolu != value))
			{
				this._resim_yolu = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.uyeol")]
public partial class uyeol : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _ad;
	
	private string _soyad;
	
	private string _kullanici_adi;
	
	private string _mail;
	
	private string _telefon;
	
	private string _parola;
	
	private string _kredik_no;
	
	private string _k_guvenlik_no;
	
	private string _k_tipi;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnadChanging(string value);
    partial void OnadChanged();
    partial void OnsoyadChanging(string value);
    partial void OnsoyadChanged();
    partial void Onkullanici_adiChanging(string value);
    partial void Onkullanici_adiChanged();
    partial void OnmailChanging(string value);
    partial void OnmailChanged();
    partial void OntelefonChanging(string value);
    partial void OntelefonChanged();
    partial void OnparolaChanging(string value);
    partial void OnparolaChanged();
    partial void Onkredik_noChanging(string value);
    partial void Onkredik_noChanged();
    partial void Onk_guvenlik_noChanging(string value);
    partial void Onk_guvenlik_noChanged();
    partial void Onk_tipiChanging(string value);
    partial void Onk_tipiChanged();
    #endregion
	
	public uyeol()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ad", DbType="NVarChar(50)")]
	public string ad
	{
		get
		{
			return this._ad;
		}
		set
		{
			if ((this._ad != value))
			{
				this.OnadChanging(value);
				this.SendPropertyChanging();
				this._ad = value;
				this.SendPropertyChanged("ad");
				this.OnadChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soyad", DbType="NVarChar(50)")]
	public string soyad
	{
		get
		{
			return this._soyad;
		}
		set
		{
			if ((this._soyad != value))
			{
				this.OnsoyadChanging(value);
				this.SendPropertyChanging();
				this._soyad = value;
				this.SendPropertyChanged("soyad");
				this.OnsoyadChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kullanici_adi", DbType="NVarChar(50)")]
	public string kullanici_adi
	{
		get
		{
			return this._kullanici_adi;
		}
		set
		{
			if ((this._kullanici_adi != value))
			{
				this.Onkullanici_adiChanging(value);
				this.SendPropertyChanging();
				this._kullanici_adi = value;
				this.SendPropertyChanged("kullanici_adi");
				this.Onkullanici_adiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mail", DbType="NVarChar(50)")]
	public string mail
	{
		get
		{
			return this._mail;
		}
		set
		{
			if ((this._mail != value))
			{
				this.OnmailChanging(value);
				this.SendPropertyChanging();
				this._mail = value;
				this.SendPropertyChanged("mail");
				this.OnmailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefon", DbType="NVarChar(50)")]
	public string telefon
	{
		get
		{
			return this._telefon;
		}
		set
		{
			if ((this._telefon != value))
			{
				this.OntelefonChanging(value);
				this.SendPropertyChanging();
				this._telefon = value;
				this.SendPropertyChanged("telefon");
				this.OntelefonChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parola", DbType="NVarChar(50)")]
	public string parola
	{
		get
		{
			return this._parola;
		}
		set
		{
			if ((this._parola != value))
			{
				this.OnparolaChanging(value);
				this.SendPropertyChanging();
				this._parola = value;
				this.SendPropertyChanged("parola");
				this.OnparolaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kredik_no", DbType="NVarChar(50)")]
	public string kredik_no
	{
		get
		{
			return this._kredik_no;
		}
		set
		{
			if ((this._kredik_no != value))
			{
				this.Onkredik_noChanging(value);
				this.SendPropertyChanging();
				this._kredik_no = value;
				this.SendPropertyChanged("kredik_no");
				this.Onkredik_noChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_k_guvenlik_no", DbType="NVarChar(50)")]
	public string k_guvenlik_no
	{
		get
		{
			return this._k_guvenlik_no;
		}
		set
		{
			if ((this._k_guvenlik_no != value))
			{
				this.Onk_guvenlik_noChanging(value);
				this.SendPropertyChanging();
				this._k_guvenlik_no = value;
				this.SendPropertyChanged("k_guvenlik_no");
				this.Onk_guvenlik_noChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_k_tipi", DbType="NVarChar(50)")]
	public string k_tipi
	{
		get
		{
			return this._k_tipi;
		}
		set
		{
			if ((this._k_tipi != value))
			{
				this.Onk_tipiChanging(value);
				this.SendPropertyChanging();
				this._k_tipi = value;
				this.SendPropertyChanged("k_tipi");
				this.Onk_tipiChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.yatak_odasi")]
public partial class yatak_odasi : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _no;
	
	private string _m_adi;
	
	private string _m_resim_yolu;
	
	private string _m_boyut;
	
	private string _m_renk;
	
	private string _kumas_adi;
	
	private string _kumas_renk;
	
	private string _kumas_resim_yolu;
	
	private string _agac_cinsi;
	
	private string _fiyat;
	
	private string _indirim_fiyat;
	
	private string _kategori;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnoChanging(string value);
    partial void OnnoChanged();
    partial void Onm_adiChanging(string value);
    partial void Onm_adiChanged();
    partial void Onm_resim_yoluChanging(string value);
    partial void Onm_resim_yoluChanged();
    partial void Onm_boyutChanging(string value);
    partial void Onm_boyutChanged();
    partial void Onm_renkChanging(string value);
    partial void Onm_renkChanged();
    partial void Onkumas_adiChanging(string value);
    partial void Onkumas_adiChanged();
    partial void Onkumas_renkChanging(string value);
    partial void Onkumas_renkChanged();
    partial void Onkumas_resim_yoluChanging(string value);
    partial void Onkumas_resim_yoluChanged();
    partial void Onagac_cinsiChanging(string value);
    partial void Onagac_cinsiChanged();
    partial void OnfiyatChanging(string value);
    partial void OnfiyatChanged();
    partial void Onindirim_fiyatChanging(string value);
    partial void Onindirim_fiyatChanged();
    partial void OnkategoriChanging(string value);
    partial void OnkategoriChanged();
    #endregion
	
	public yatak_odasi()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_no", DbType="NVarChar(50)")]
	public string no
	{
		get
		{
			return this._no;
		}
		set
		{
			if ((this._no != value))
			{
				this.OnnoChanging(value);
				this.SendPropertyChanging();
				this._no = value;
				this.SendPropertyChanged("no");
				this.OnnoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_m_adi", DbType="NVarChar(50)")]
	public string m_adi
	{
		get
		{
			return this._m_adi;
		}
		set
		{
			if ((this._m_adi != value))
			{
				this.Onm_adiChanging(value);
				this.SendPropertyChanging();
				this._m_adi = value;
				this.SendPropertyChanged("m_adi");
				this.Onm_adiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_m_resim_yolu", DbType="NVarChar(200)")]
	public string m_resim_yolu
	{
		get
		{
			return this._m_resim_yolu;
		}
		set
		{
			if ((this._m_resim_yolu != value))
			{
				this.Onm_resim_yoluChanging(value);
				this.SendPropertyChanging();
				this._m_resim_yolu = value;
				this.SendPropertyChanged("m_resim_yolu");
				this.Onm_resim_yoluChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_m_boyut", DbType="NVarChar(50)")]
	public string m_boyut
	{
		get
		{
			return this._m_boyut;
		}
		set
		{
			if ((this._m_boyut != value))
			{
				this.Onm_boyutChanging(value);
				this.SendPropertyChanging();
				this._m_boyut = value;
				this.SendPropertyChanged("m_boyut");
				this.Onm_boyutChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_m_renk", DbType="NVarChar(50)")]
	public string m_renk
	{
		get
		{
			return this._m_renk;
		}
		set
		{
			if ((this._m_renk != value))
			{
				this.Onm_renkChanging(value);
				this.SendPropertyChanging();
				this._m_renk = value;
				this.SendPropertyChanged("m_renk");
				this.Onm_renkChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kumas_adi", DbType="NVarChar(50)")]
	public string kumas_adi
	{
		get
		{
			return this._kumas_adi;
		}
		set
		{
			if ((this._kumas_adi != value))
			{
				this.Onkumas_adiChanging(value);
				this.SendPropertyChanging();
				this._kumas_adi = value;
				this.SendPropertyChanged("kumas_adi");
				this.Onkumas_adiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kumas_renk", DbType="NVarChar(50)")]
	public string kumas_renk
	{
		get
		{
			return this._kumas_renk;
		}
		set
		{
			if ((this._kumas_renk != value))
			{
				this.Onkumas_renkChanging(value);
				this.SendPropertyChanging();
				this._kumas_renk = value;
				this.SendPropertyChanged("kumas_renk");
				this.Onkumas_renkChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kumas_resim_yolu", DbType="NVarChar(200)")]
	public string kumas_resim_yolu
	{
		get
		{
			return this._kumas_resim_yolu;
		}
		set
		{
			if ((this._kumas_resim_yolu != value))
			{
				this.Onkumas_resim_yoluChanging(value);
				this.SendPropertyChanging();
				this._kumas_resim_yolu = value;
				this.SendPropertyChanged("kumas_resim_yolu");
				this.Onkumas_resim_yoluChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_agac_cinsi", DbType="NVarChar(50)")]
	public string agac_cinsi
	{
		get
		{
			return this._agac_cinsi;
		}
		set
		{
			if ((this._agac_cinsi != value))
			{
				this.Onagac_cinsiChanging(value);
				this.SendPropertyChanging();
				this._agac_cinsi = value;
				this.SendPropertyChanged("agac_cinsi");
				this.Onagac_cinsiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fiyat", DbType="NVarChar(50)")]
	public string fiyat
	{
		get
		{
			return this._fiyat;
		}
		set
		{
			if ((this._fiyat != value))
			{
				this.OnfiyatChanging(value);
				this.SendPropertyChanging();
				this._fiyat = value;
				this.SendPropertyChanged("fiyat");
				this.OnfiyatChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_indirim_fiyat", DbType="NVarChar(50)")]
	public string indirim_fiyat
	{
		get
		{
			return this._indirim_fiyat;
		}
		set
		{
			if ((this._indirim_fiyat != value))
			{
				this.Onindirim_fiyatChanging(value);
				this.SendPropertyChanging();
				this._indirim_fiyat = value;
				this.SendPropertyChanged("indirim_fiyat");
				this.Onindirim_fiyatChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kategori", DbType="NVarChar(50)")]
	public string kategori
	{
		get
		{
			return this._kategori;
		}
		set
		{
			if ((this._kategori != value))
			{
				this.OnkategoriChanging(value);
				this.SendPropertyChanging();
				this._kategori = value;
				this.SendPropertyChanged("kategori");
				this.OnkategoriChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.yemek_odasi")]
public partial class yemek_odasi : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _no;
	
	private string _m_adi;
	
	private string _m_resim_yolu;
	
	private string _m_boyut;
	
	private string _m_renk;
	
	private string _kumas_adi;
	
	private string _kumas_renk;
	
	private string _agac_cinsi;
	
	private string _fiyat;
	
	private string _indirim_fiyat;
	
	private string _kategori;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnoChanging(string value);
    partial void OnnoChanged();
    partial void Onm_adiChanging(string value);
    partial void Onm_adiChanged();
    partial void Onm_resim_yoluChanging(string value);
    partial void Onm_resim_yoluChanged();
    partial void Onm_boyutChanging(string value);
    partial void Onm_boyutChanged();
    partial void Onm_renkChanging(string value);
    partial void Onm_renkChanged();
    partial void Onkumas_adiChanging(string value);
    partial void Onkumas_adiChanged();
    partial void Onkumas_renkChanging(string value);
    partial void Onkumas_renkChanged();
    partial void Onagac_cinsiChanging(string value);
    partial void Onagac_cinsiChanged();
    partial void OnfiyatChanging(string value);
    partial void OnfiyatChanged();
    partial void Onindirim_fiyatChanging(string value);
    partial void Onindirim_fiyatChanged();
    partial void OnkategoriChanging(string value);
    partial void OnkategoriChanged();
    #endregion
	
	public yemek_odasi()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_no", DbType="NVarChar(50)")]
	public string no
	{
		get
		{
			return this._no;
		}
		set
		{
			if ((this._no != value))
			{
				this.OnnoChanging(value);
				this.SendPropertyChanging();
				this._no = value;
				this.SendPropertyChanged("no");
				this.OnnoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_m_adi", DbType="NVarChar(50)")]
	public string m_adi
	{
		get
		{
			return this._m_adi;
		}
		set
		{
			if ((this._m_adi != value))
			{
				this.Onm_adiChanging(value);
				this.SendPropertyChanging();
				this._m_adi = value;
				this.SendPropertyChanged("m_adi");
				this.Onm_adiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_m_resim_yolu", DbType="NVarChar(200)")]
	public string m_resim_yolu
	{
		get
		{
			return this._m_resim_yolu;
		}
		set
		{
			if ((this._m_resim_yolu != value))
			{
				this.Onm_resim_yoluChanging(value);
				this.SendPropertyChanging();
				this._m_resim_yolu = value;
				this.SendPropertyChanged("m_resim_yolu");
				this.Onm_resim_yoluChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_m_boyut", DbType="NVarChar(50)")]
	public string m_boyut
	{
		get
		{
			return this._m_boyut;
		}
		set
		{
			if ((this._m_boyut != value))
			{
				this.Onm_boyutChanging(value);
				this.SendPropertyChanging();
				this._m_boyut = value;
				this.SendPropertyChanged("m_boyut");
				this.Onm_boyutChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_m_renk", DbType="NVarChar(50)")]
	public string m_renk
	{
		get
		{
			return this._m_renk;
		}
		set
		{
			if ((this._m_renk != value))
			{
				this.Onm_renkChanging(value);
				this.SendPropertyChanging();
				this._m_renk = value;
				this.SendPropertyChanged("m_renk");
				this.Onm_renkChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kumas_adi", DbType="NVarChar(50)")]
	public string kumas_adi
	{
		get
		{
			return this._kumas_adi;
		}
		set
		{
			if ((this._kumas_adi != value))
			{
				this.Onkumas_adiChanging(value);
				this.SendPropertyChanging();
				this._kumas_adi = value;
				this.SendPropertyChanged("kumas_adi");
				this.Onkumas_adiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kumas_renk", DbType="NVarChar(50)")]
	public string kumas_renk
	{
		get
		{
			return this._kumas_renk;
		}
		set
		{
			if ((this._kumas_renk != value))
			{
				this.Onkumas_renkChanging(value);
				this.SendPropertyChanging();
				this._kumas_renk = value;
				this.SendPropertyChanged("kumas_renk");
				this.Onkumas_renkChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_agac_cinsi", DbType="NVarChar(50)")]
	public string agac_cinsi
	{
		get
		{
			return this._agac_cinsi;
		}
		set
		{
			if ((this._agac_cinsi != value))
			{
				this.Onagac_cinsiChanging(value);
				this.SendPropertyChanging();
				this._agac_cinsi = value;
				this.SendPropertyChanged("agac_cinsi");
				this.Onagac_cinsiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fiyat", DbType="NVarChar(50)")]
	public string fiyat
	{
		get
		{
			return this._fiyat;
		}
		set
		{
			if ((this._fiyat != value))
			{
				this.OnfiyatChanging(value);
				this.SendPropertyChanging();
				this._fiyat = value;
				this.SendPropertyChanged("fiyat");
				this.OnfiyatChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_indirim_fiyat", DbType="NVarChar(50)")]
	public string indirim_fiyat
	{
		get
		{
			return this._indirim_fiyat;
		}
		set
		{
			if ((this._indirim_fiyat != value))
			{
				this.Onindirim_fiyatChanging(value);
				this.SendPropertyChanging();
				this._indirim_fiyat = value;
				this.SendPropertyChanged("indirim_fiyat");
				this.Onindirim_fiyatChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kategori", DbType="NVarChar(50)")]
	public string kategori
	{
		get
		{
			return this._kategori;
		}
		set
		{
			if ((this._kategori != value))
			{
				this.OnkategoriChanging(value);
				this.SendPropertyChanging();
				this._kategori = value;
				this.SendPropertyChanged("kategori");
				this.OnkategoriChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.yonetici")]
public partial class yonetici : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _yonetici_adi;
	
	private string _parola;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onyonetici_adiChanging(string value);
    partial void Onyonetici_adiChanged();
    partial void OnparolaChanging(string value);
    partial void OnparolaChanged();
    #endregion
	
	public yonetici()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_yonetici_adi", DbType="NVarChar(25)")]
	public string yonetici_adi
	{
		get
		{
			return this._yonetici_adi;
		}
		set
		{
			if ((this._yonetici_adi != value))
			{
				this.Onyonetici_adiChanging(value);
				this.SendPropertyChanging();
				this._yonetici_adi = value;
				this.SendPropertyChanged("yonetici_adi");
				this.Onyonetici_adiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parola", DbType="NVarChar(25)")]
	public string parola
	{
		get
		{
			return this._parola;
		}
		set
		{
			if ((this._parola != value))
			{
				this.OnparolaChanging(value);
				this.SendPropertyChanging();
				this._parola = value;
				this.SendPropertyChanged("parola");
				this.OnparolaChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
